# Generated by Django 3.2.6 on 2021-12-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL_link')),
                ('image_files', models.FileField(upload_to='pdf_files/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course_storage',
            },
        ),
    ]
