# Generated by Django 3.2.6 on 2021-10-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='donor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor', to='billing.bankaccount', verbose_name='donor_account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='billing.bankaccount', verbose_name='recipient_account'),
        ),
    ]
